#!/bin/bash

# 3. Three is a Charm. Write a script of you choice.

# Description: cat and execute init script
# Author: slisandr

if [[ ! $# -eq 2 || ! $1 = [NnSs] || ! $2 =~ ^[0-9]?[0-9][ab]?[_]?$ ]]; then
	echo "Usage: show_init [ns] [0-9][0-9]" >&2
	exit 1
fi

if [[ $1 = [Nn] && -e ../network/$2 ]]; then
	clear
	cat "../network/$2"
	echo "===========Output==========="
	sh "../network/$2"
	echo "=============End============"
	printf "\n\n\n"
elif [[ $1 = [Ss] && -e ../system/$2 ]]; then
	clear
	cat "../system/$2"
	echo "===========Output==========="
	sh "../system/$2"
	echo "=============End============"
	printf "\n\n\n"
else
	echo "Requested file doesn't exist" >&2
	exit 1
fi

exit 0
